# Generated by Django 2.2.14 on 2020-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='client_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='client_key',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
