# Generated by Django 2.2.14 on 2020-07-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0002_auto_20200704_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_cert', models.FileField(blank=True, help_text='.pem', null=True, upload_to='certificates/')),
                ('client_key', models.FileField(blank=True, help_text='.pem', null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=4096)),
                ('http_method', models.CharField(choices=[('get', 'GET'), ('post', 'POST')], default='get', max_length=8)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('expected_response_code', models.CharField(blank=True, help_text='Regular Expression', max_length=8, null=True)),
                ('expected_response_body', models.TextField(blank=True, help_text='Regular Expression', null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='healthCheck',
        ),
    ]
