# Generated by Django 2.2.14 on 2020-07-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0004_auto_20200705_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcertificate',
            name='client_cert',
            field=models.FileField(default=None, help_text='Use .pem cert file', upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
