# Generated by Django 2.2.14 on 2020-07-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0005_auto_20200705_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckrecord',
            name='health_check_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HealthChecker.HealthCheckRule'),
        ),
        migrations.AlterField(
            model_name='healthcheckrecord',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckrecord',
            name='response_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckrecord',
            name='response_delay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
