# Generated by Django 2.2.14 on 2020-07-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0007_auto_20200705_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckrule',
            name='expected_response_body',
            field=models.TextField(blank=True, default='.*', help_text='Regular Expression', null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckrule',
            name='expected_response_code',
            field=models.CharField(blank=True, default='200', help_text='Regular Expression', max_length=8, null=True),
        ),
    ]
