# Generated by Django 2.2.14 on 2020-07-30 09:13

from django.db import models, migrations
from django.contrib.auth.models import User
import os

def apply_migration(apps, schema_editor):
    User.objects.create_superuser(os.environ.get('AWT_ADMIN', 'admin'), os.environ.get('AWT_EMAIL', 'admin@django.com'), os.environ.get('AWT_PASS', 'admin'))

def revert_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0008_auto_20200708_1902'),
        #('contenttypes', '__latest__'),
        #('auth', '__latest__'),
        #('admin', '__latest__'),
        #('dashboard', '__latest__'),
        #('sessions', '__latest__'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
