# Generated by Django 2.2.14 on 2020-07-30 09:13

from django.db import models, migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    members = Group.objects.create(name='members')
    permissions = Permission.objects.all().exclude(codename__in=['delete_permission',
                                                                 'change_permission', 'add_permission', 'add_group',
                                                                 'change_group', 'delete_group', 'add_user', 'delete_user'
                                                                 'change_user', 'add_contenttype', 'change_contenttype',
                                                                 'delete_contenttype', 'add_logentry', 'change_logentry',
                                                                 'delete_logentry', 'add_session', 'change_session',
                                                                 'delete_session'])
    members.permissions.add(*permissions)
    admins = Group.objects.create(name='admins')
    admins_permissions = Permission.objects.all()
    admins.permissions.add(*admins_permissions)

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            'members',
            'admins'
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0008_auto_20200708_1902'),
        #('contenttypes', '__latest__'),
        #('auth', '__latest__'),
        #('admin', '__latest__'),
        #('dashboard', '__latest__'),
        #('sessions', '__latest__'),
    ]

    operations = [
        #migrations.RunPython(apply_migration, revert_migration)
    ]
