# Generated by Django 2.2.17 on 2020-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0009_auto_20200730_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckrule',
            name='output_variables',
            field=models.TextField(blank=True, default='', help_text='keys seperated by comma', null=True),
        ),
    ]
