# Generated by Django 2.2.19 on 2021-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthChecker', '0013_environmentvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
