# docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres:13
    container_name: 'awt_app_postgres'
    restart: always
    environment:
      - POSTGRES_DB=AWT
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresDatas:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: 'awt_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'awt_app_django'
    command: bash -c 'python manage.py migrate auth && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      - AAD_TENANT_ID=xxxxx
      - AAD_CLIENT_ID=xxxxx
  celery:
    build: .
    container_name: 'awt_app_celery'
    command: celery -A ApiWatchTower worker -B --concurrency=10
    links:
      - redis
    depends_on:
      - web
      - redis
      - postgres
    environment:
      - AAD_TENANT_ID=xxxxx
      - AAD_CLIENT_ID=xxxxx
  celery-beat:
    build: .
    restart: always
    container_name: 'awt_celery_beat'
    command: celery -A ApiWatchTower beat -l info -S django --pidfile=
    links:
      - redis
    depends_on:
      - web
      - redis
      - celery
      - postgres
    environment:
      - AAD_TENANT_ID=xxxxx
      - AAD_CLIENT_ID=xxxxx
  grafana:
    image: grafana/grafana:latest
    container_name: 'awt_grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=abozar

volumes:
    postgresDatas: