{
 "title": "Dashboard Template",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Tags",
    "query": "select unnest(STRING_TO_ARRAY(REGEXP_REPLACE(description, '\\s+', ' '), ' '))\nFROM \"HealthChecker_healthcheckrule\""
   },
   { "name": "Relation", "query": "Any,All" }
  ]
 },
 "panels": [
  {
   "title": "Admin",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://localhost/admin\"><img src=\"http://localhost/admin/static/favicon.png\" width=\"auto\" height=\"auto\"  /></a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay\nFROM \"HealthChecker_healthcheckrecord\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Health",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(success AS INT) / response_delay,\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\") \n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Delay",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"timestamp\" AS \"time\",\r\n  response_delay,\r\n  \"HealthChecker_healthcheckrule\".name\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") \r\n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "alert list",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay\nFROM \"HealthChecker_healthcheckrecord\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Response Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay * CAST(success AS int),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\") --and success \n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\n  -- and description LIKE '%${TAGS:raw}%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Success",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(success AS INT),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\")\n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(response_code AS INT),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\")\n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"HealthChecker_healthcheckrule\".name,\r\n  response_code,\r\n  response_delay,\r\n  success,\r\n  error,\r\n  \"timestamp\" AS \"time\",\r\n  response_body,\r\n  error_description\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\")\r\n  and description ~ ${Relation}(STRING_TO_ARRAY('${Tags:raw}', ','))\r\nORDER BY timestamp desc\r\nlimit 20"
    }
   ]
  }
 ]
}