{
 "title": "AWT Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Admin",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://localhost/\"><img src=\"http://localhost/static/favicon.png\" width=\"auto\" height=\"auto\"  /></a>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay\nFROM \"HealthChecker_healthcheckrecord\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "alert list",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay\nFROM \"HealthChecker_healthcheckrecord\"\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Delay",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"timestamp\" AS \"time\",\r\n  response_delay,\r\n  \"HealthChecker_healthcheckrule\".name\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") \r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Google Delay",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"timestamp\" AS \"time\",\r\n  response_delay,\r\n  \"HealthChecker_healthcheckrule\".name as name\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") and \"HealthChecker_healthcheckrule\".name in('google')\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Microsoft Delay",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"timestamp\" AS \"time\",\r\n  response_delay,\r\n  \"HealthChecker_healthcheckrule\".name as name\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") and \"HealthChecker_healthcheckrule\".name in('microsoft')\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "amazon Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"timestamp\" AS \"time\",\r\n  CAST(response_code AS INT),\r\n  \"HealthChecker_healthcheckrule\".name as name\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") and \"HealthChecker_healthcheckrule\".name in('amazon')\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Response Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  response_delay,\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\") and success \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Success",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(success AS INT),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Health",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(success AS INT),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\") \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  CAST(response_code AS INT),\n  \"HealthChecker_healthcheckrule\".name\nFROM \"HealthChecker_healthcheckrecord\"\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"HealthChecker_healthcheckrule\".name,\r\n  response_code,\r\n  response_delay,\r\n  success,\r\n  error,\r\n  \"timestamp\" AS \"time\",\r\n  response_body,\r\n  error_description\r\nFROM \"HealthChecker_healthcheckrecord\"\r\nINNER JOIN \"HealthChecker_healthcheckrule\" on \"HealthChecker_healthcheckrule\".id = health_check_rule_id\r\nWHERE\r\n  $__timeFilter(\"timestamp\") \r\nORDER BY timestamp desc\r\nlimit 20"
    }
   ]
  }
 ]
}